import numpy as np
import pandas as pd
import json

def validate_map_data(clustered_df, anomalies_df, disease_name):
    subset = clustered_df[clustered_df['disease'] == disease_name]
    heat_data = subset[['lat', 'lon', 'weight']].values.tolist()
    markers = anomalies_df[anomalies_df['disease'] == disease_name]
    return {
        'disease': disease_name,
        'heatmap_points': len(heat_data),
        'map_center': [subset['lat'].mean(), subset['lon'].mean()],
        'total_markers': len(markers),
        'anomaly_markers': int(markers['is_anomaly'].sum()),
        'normal_markers': int((~markers['is_anomaly']).sum()),
    }

def generate_alerts(anomalies_df):
    alerts = anomalies_df[anomalies_df['is_anomaly'] == True].copy()
    if alerts.empty:
        print("   ℹ️  No alerts to generate.")
        return alerts
    for _, alert in alerts.iterrows():
        print(f"""
        ⚠️  OUTBREAK ALERT
        Disease   : {alert['disease']}
        Cluster   : {alert['cluster_id']}
        Location  : ({alert['centroid_lat']:.4f}, {alert['centroid_lon']:.4f})
        Period    : {alert['time_window']}
        Cases     : {int(alert['case_count'])}
        """)
    return alerts

def export_to_frontend(patient_df, clustered_dfs, scan_results, output_path='js/data.js'):
    cluster_map = {}
    for disease, cdf in clustered_dfs.items():
        for _, row in cdf.iterrows():
            cluster_map[(row['patient_id'], row['location_type'])] = row['cluster_id']

    anom_map = {}
    for _, row in scan_results.iterrows():
        anom_map[(row['cluster_id'], row['disease'], str(row['time_window']))] = row['is_anomaly']

    patients_list = []
    start_date = pd.to_datetime(patient_df['record_date'].min())

    for _, row in patient_df.iterrows():
        pid = row['patient_id']
        disease = row['predicted_disease']
        date = pd.to_datetime(row['record_date'])
        week_num = (date - start_date).days // 7
        
        cid = cluster_map.get((pid, 'home'), -1)
        time_window_str = str(date.to_period('W'))
        is_anom = anom_map.get((cid, disease, time_window_str), False)
        
        patients_list.append({
            'id': pid,
            'home': {'lat': row['home_lat'], 'lng': row['home_lon']},
            'work': {'lat': row['work_lat'], 'lng': row['work_lon']},
            'disease': disease,
            'conf': row['confidence'],
            'week': int(week_num),
            'isAnom': bool(is_anom),
            'cid': int(cid),
            'date': row['record_date']
        })

    js_content = f"""// AUTO-GENERATED BY PYTHON PIPELINE
const PATIENTS = {json.dumps(patients_list, indent=2)};

const COLORS = {{
  Dengue:  '#E85D30',
  Cholera: '#2B7FD4',
  Typhoid: '#16A37A',
}};
"""

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(js_content)
    
    print(f"✅ Successfully exported {len(patients_list)} patients to {output_path}")

